/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardHomeIndexRouteImport } from './routes/dashboard/home/index'
import { Route as DashboardExperimentsSingleAgentIndexRouteImport } from './routes/dashboard/experiments/single-agent/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHomeIndexRoute = DashboardHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExperimentsSingleAgentIndexRoute =
  DashboardExperimentsSingleAgentIndexRouteImport.update({
    id: '/experiments/single-agent/',
    path: '/experiments/single-agent/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/home/': typeof DashboardHomeIndexRoute
  '/dashboard/experiments/single-agent/': typeof DashboardExperimentsSingleAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/home': typeof DashboardHomeIndexRoute
  '/dashboard/experiments/single-agent': typeof DashboardExperimentsSingleAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/home/': typeof DashboardHomeIndexRoute
  '/dashboard/experiments/single-agent/': typeof DashboardExperimentsSingleAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/home/'
    | '/dashboard/experiments/single-agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/home'
    | '/dashboard/experiments/single-agent'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/home/'
    | '/dashboard/experiments/single-agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/home/': {
      id: '/dashboard/home/'
      path: '/home'
      fullPath: '/dashboard/home/'
      preLoaderRoute: typeof DashboardHomeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/experiments/single-agent/': {
      id: '/dashboard/experiments/single-agent/'
      path: '/experiments/single-agent'
      fullPath: '/dashboard/experiments/single-agent/'
      preLoaderRoute: typeof DashboardExperimentsSingleAgentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardHomeIndexRoute: typeof DashboardHomeIndexRoute
  DashboardExperimentsSingleAgentIndexRoute: typeof DashboardExperimentsSingleAgentIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardHomeIndexRoute: DashboardHomeIndexRoute,
  DashboardExperimentsSingleAgentIndexRoute:
    DashboardExperimentsSingleAgentIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
