// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/ws/type.go
//
// Generated by this command:
//
//	mockgen -source internal/pkg/ws/type.go -destination test/_mocks/ws/mock_type.go
//

// Package mock_ws is a generated GoMock package.
package mock_ws

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWsConnection is a mock of WsConnection interface.
type MockWsConnection struct {
	ctrl     *gomock.Controller
	recorder *MockWsConnectionMockRecorder
	isgomock struct{}
}

// MockWsConnectionMockRecorder is the mock recorder for MockWsConnection.
type MockWsConnectionMockRecorder struct {
	mock *MockWsConnection
}

// NewMockWsConnection creates a new mock instance.
func NewMockWsConnection(ctrl *gomock.Controller) *MockWsConnection {
	mock := &MockWsConnection{ctrl: ctrl}
	mock.recorder = &MockWsConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWsConnection) EXPECT() *MockWsConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWsConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWsConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWsConnection)(nil).Close))
}

// ReadJSON mocks base method.
func (m *MockWsConnection) ReadJSON(v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadJSON", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadJSON indicates an expected call of ReadJSON.
func (mr *MockWsConnectionMockRecorder) ReadJSON(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadJSON", reflect.TypeOf((*MockWsConnection)(nil).ReadJSON), v)
}

// ReadMessage mocks base method.
func (m *MockWsConnection) ReadMessage() (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMessage")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadMessage indicates an expected call of ReadMessage.
func (mr *MockWsConnectionMockRecorder) ReadMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMessage", reflect.TypeOf((*MockWsConnection)(nil).ReadMessage))
}

// WriteJSON mocks base method.
func (m *MockWsConnection) WriteJSON(message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJSON", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJSON indicates an expected call of WriteJSON.
func (mr *MockWsConnectionMockRecorder) WriteJSON(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJSON", reflect.TypeOf((*MockWsConnection)(nil).WriteJSON), message)
}

// WriteMessage mocks base method.
func (m *MockWsConnection) WriteMessage(mt int, message []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMessage", mt, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessage indicates an expected call of WriteMessage.
func (mr *MockWsConnectionMockRecorder) WriteMessage(mt, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessage", reflect.TypeOf((*MockWsConnection)(nil).WriteMessage), mt, message)
}

// MockWsHandler is a mock of WsHandler interface.
type MockWsHandler struct {
	ctrl     *gomock.Controller
	recorder *MockWsHandlerMockRecorder
	isgomock struct{}
}

// MockWsHandlerMockRecorder is the mock recorder for MockWsHandler.
type MockWsHandlerMockRecorder struct {
	mock *MockWsHandler
}

// NewMockWsHandler creates a new mock instance.
func NewMockWsHandler(ctrl *gomock.Controller) *MockWsHandler {
	mock := &MockWsHandler{ctrl: ctrl}
	mock.recorder = &MockWsHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWsHandler) EXPECT() *MockWsHandlerMockRecorder {
	return m.recorder
}

// HandleConnection mocks base method.
func (m *MockWsHandler) HandleConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleConnection indicates an expected call of HandleConnection.
func (mr *MockWsHandlerMockRecorder) HandleConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConnection", reflect.TypeOf((*MockWsHandler)(nil).HandleConnection))
}
