mode: dev

openai:
  api_key: "sk-proj-1234567890"

server:
  port: 8081

websocket:
  port: 8082

database:
  host: localhost
  port: 5432
  user: lucid
  password: "12345678"
  dbname: lucid

milvus:
  address: localhost:19530
  dimension: 1536

kafka:
  address: localhost:9092

worker:
  ticker_interval: 500ms
  worker_control_ch_size: 10
  publish_timeout: 5s

agent_controller:
  agent_life_time: 10s
  scan_interval: 1s
  max_resp_ch_size: 10

scheduler:
  scheduler_control_ch_size: 10
  scan_interval: 1s
  agent_sleep_duration: 10s
  agent_awake_duration: 5m
  batch_process_agent_num: 10
