mode: dev

openai:
  api_key: "sk-proj-1234567890"

server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: lucid
  password: "12345678"
  dbname: lucid

milvus:
  address: localhost:19530
  dimension: 1536

kafka:
  address: localhost:9092
