// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/agents/type.go
//
// Generated by this command:
//
//	mockgen -source internal/pkg/agents/type.go -destination test/_mocks/agents/mock_type.go
//

// Package mock_agents is a generated GoMock package.
package mock_agents

import (
	context "context"
	reflect "reflect"

	agents "github.com/roackb2/lucid/internal/pkg/agents"
	worker "github.com/roackb2/lucid/internal/pkg/agents/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockAgent is a mock of Agent interface.
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
	isgomock struct{}
}

// MockAgentMockRecorder is the mock recorder for MockAgent.
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance.
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAgent) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAgentMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAgent)(nil).Close))
}

// GetID mocks base method.
func (m *MockAgent) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockAgentMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockAgent)(nil).GetID))
}

// GetStatus mocks base method.
func (m *MockAgent) GetStatus() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockAgentMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockAgent)(nil).GetStatus))
}

// PersistState mocks base method.
func (m *MockAgent) PersistState() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistState")
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistState indicates an expected call of PersistState.
func (mr *MockAgentMockRecorder) PersistState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistState", reflect.TypeOf((*MockAgent)(nil).PersistState))
}

// ResumeTask mocks base method.
func (m *MockAgent) ResumeTask(ctx context.Context, agentID string, newPrompt *string, callbacks worker.WorkerCallbacks) (*agents.AgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeTask", ctx, agentID, newPrompt, callbacks)
	ret0, _ := ret[0].(*agents.AgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeTask indicates an expected call of ResumeTask.
func (mr *MockAgentMockRecorder) ResumeTask(ctx, agentID, newPrompt, callbacks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeTask", reflect.TypeOf((*MockAgent)(nil).ResumeTask), ctx, agentID, newPrompt, callbacks)
}

// SendCommand mocks base method.
func (m *MockAgent) SendCommand(ctx context.Context, command string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCommand", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCommand indicates an expected call of SendCommand.
func (mr *MockAgentMockRecorder) SendCommand(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCommand", reflect.TypeOf((*MockAgent)(nil).SendCommand), ctx, command)
}

// StartTask mocks base method.
func (m *MockAgent) StartTask(ctx context.Context, callbacks worker.WorkerCallbacks) (*agents.AgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTask", ctx, callbacks)
	ret0, _ := ret[0].(*agents.AgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTask indicates an expected call of StartTask.
func (mr *MockAgentMockRecorder) StartTask(ctx, callbacks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTask", reflect.TypeOf((*MockAgent)(nil).StartTask), ctx, callbacks)
}
