// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_states.sql

package dbaccess

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentState = `-- name: CreateAgentState :exec
INSERT INTO agent_states (agent_id, state, status, awakened_at, asleep_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateAgentStateParams struct {
	AgentID    string
	State      []byte
	Status     string
	AwakenedAt pgtype.Timestamp
	AsleepAt   pgtype.Timestamp
}

func (q *Queries) CreateAgentState(ctx context.Context, arg CreateAgentStateParams) error {
	_, err := q.db.Exec(ctx, createAgentState,
		arg.AgentID,
		arg.State,
		arg.Status,
		arg.AwakenedAt,
		arg.AsleepAt,
	)
	return err
}

const getAgentState = `-- name: GetAgentState :one
SELECT id, agent_id, status, state, created_at, updated_at, awakened_at, asleep_at FROM agent_states WHERE agent_id = $1
`

func (q *Queries) GetAgentState(ctx context.Context, agentID string) (AgentState, error) {
	row := q.db.QueryRow(ctx, getAgentState, agentID)
	var i AgentState
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Status,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AwakenedAt,
		&i.AsleepAt,
	)
	return i, err
}

const searchAgentByStatus = `-- name: SearchAgentByStatus :many
SELECT id, agent_id, status, state, created_at, updated_at, awakened_at, asleep_at FROM agent_states WHERE status = $1
`

func (q *Queries) SearchAgentByStatus(ctx context.Context, status string) ([]AgentState, error) {
	rows, err := q.db.Query(ctx, searchAgentByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentState
	for rows.Next() {
		var i AgentState
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Status,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AwakenedAt,
			&i.AsleepAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentState = `-- name: UpdateAgentState :exec
UPDATE agent_states SET status = $2, state = $3, awakened_at = $4, asleep_at = $5 WHERE agent_id = $1
`

type UpdateAgentStateParams struct {
	AgentID    string
	Status     string
	State      []byte
	AwakenedAt pgtype.Timestamp
	AsleepAt   pgtype.Timestamp
}

func (q *Queries) UpdateAgentState(ctx context.Context, arg UpdateAgentStateParams) error {
	_, err := q.db.Exec(ctx, updateAgentState,
		arg.AgentID,
		arg.Status,
		arg.State,
		arg.AwakenedAt,
		arg.AsleepAt,
	)
	return err
}
