// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_profiles.sql

package dbaccess

import (
	"context"
)

const createAgentProfile = `-- name: CreateAgentProfile :exec
INSERT INTO agent_profiles (agent_id, profile)
VALUES ($1, $2)
`

type CreateAgentProfileParams struct {
	AgentID string
	Profile string
}

func (q *Queries) CreateAgentProfile(ctx context.Context, arg CreateAgentProfileParams) error {
	_, err := q.db.Exec(ctx, createAgentProfile, arg.AgentID, arg.Profile)
	return err
}

const getAgentProfile = `-- name: GetAgentProfile :one
SELECT id, agent_id, profile, created_at, updated_at
FROM agent_profiles
WHERE agent_id = $1
`

func (q *Queries) GetAgentProfile(ctx context.Context, agentID string) (AgentProfile, error) {
	row := q.db.QueryRow(ctx, getAgentProfile, agentID)
	var i AgentProfile
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Profile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchAgentProfile = `-- name: SearchAgentProfile :many
SELECT id, agent_id, profile, created_at, updated_at
FROM agent_profiles
WHERE SIMILARITY(profile, $1::text) > 0.3
OR profile ILIKE '%' || $1 || '%'
OR profile ILIKE ANY(
  SELECT '%' || word || '%'
  FROM UNNEST(STRING_TO_ARRAY($1, ' ')) AS word
)
`

func (q *Queries) SearchAgentProfile(ctx context.Context, keyword string) ([]AgentProfile, error) {
	rows, err := q.db.Query(ctx, searchAgentProfile, keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentProfile
	for rows.Next() {
		var i AgentProfile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Profile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentProfile = `-- name: UpdateAgentProfile :exec
UPDATE agent_profiles
SET profile = $1
WHERE agent_id = $2
`

type UpdateAgentProfileParams struct {
	Profile string
	AgentID string
}

func (q *Queries) UpdateAgentProfile(ctx context.Context, arg UpdateAgentProfileParams) error {
	_, err := q.db.Exec(ctx, updateAgentProfile, arg.Profile, arg.AgentID)
	return err
}
