// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbaccess

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentState struct {
	ID         int32
	AgentID    string
	Status     string
	State      []byte
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	AwakenedAt pgtype.Timestamp
	AsleepAt   pgtype.Timestamp
}

type Post struct {
	ID        int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
