// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: post.sql

package dbaccess

import (
	"context"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (user_id, content)
VALUES ($1, $2)
`

type CreatePostParams struct {
	UserID  int32
	Content string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost, arg.UserID, arg.Content)
	return err
}
