// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/agents/tools/type.go
//
// Generated by this command:
//
//	mockgen -source internal/pkg/agents/tools/type.go -destination test/_mocks/agents/tools/mock_type.go
//

// Package mock_tools is a generated GoMock package.
package mock_tools

import (
	reflect "reflect"

	providers "github.com/roackb2/lucid/internal/pkg/agents/providers"
	gomock "go.uber.org/mock/gomock"
)

// MockPersistTool is a mock of PersistTool interface.
type MockPersistTool struct {
	ctrl     *gomock.Controller
	recorder *MockPersistToolMockRecorder
	isgomock struct{}
}

// MockPersistToolMockRecorder is the mock recorder for MockPersistTool.
type MockPersistToolMockRecorder struct {
	mock *MockPersistTool
}

// NewMockPersistTool creates a new mock instance.
func NewMockPersistTool(ctrl *gomock.Controller) *MockPersistTool {
	mock := &MockPersistTool{ctrl: ctrl}
	mock.recorder = &MockPersistToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistTool) EXPECT() *MockPersistToolMockRecorder {
	return m.recorder
}

// SaveContent mocks base method.
func (m *MockPersistTool) SaveContent(toolCall providers.ToolCall) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveContent", toolCall)
	ret0, _ := ret[0].(string)
	return ret0
}

// SaveContent indicates an expected call of SaveContent.
func (mr *MockPersistToolMockRecorder) SaveContent(toolCall any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveContent", reflect.TypeOf((*MockPersistTool)(nil).SaveContent), toolCall)
}

// SearchContent mocks base method.
func (m *MockPersistTool) SearchContent(toolCall providers.ToolCall) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContent", toolCall)
	ret0, _ := ret[0].(string)
	return ret0
}

// SearchContent indicates an expected call of SearchContent.
func (mr *MockPersistToolMockRecorder) SearchContent(toolCall any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContent", reflect.TypeOf((*MockPersistTool)(nil).SearchContent), toolCall)
}

// MockFlowTool is a mock of FlowTool interface.
type MockFlowTool struct {
	ctrl     *gomock.Controller
	recorder *MockFlowToolMockRecorder
	isgomock struct{}
}

// MockFlowToolMockRecorder is the mock recorder for MockFlowTool.
type MockFlowToolMockRecorder struct {
	mock *MockFlowTool
}

// NewMockFlowTool creates a new mock instance.
func NewMockFlowTool(ctrl *gomock.Controller) *MockFlowTool {
	mock := &MockFlowTool{ctrl: ctrl}
	mock.recorder = &MockFlowToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowTool) EXPECT() *MockFlowToolMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockFlowTool) Report(toolCall providers.ToolCall) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", toolCall)
	ret0, _ := ret[0].(string)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockFlowToolMockRecorder) Report(toolCall any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockFlowTool)(nil).Report), toolCall)
}

// Wait mocks base method.
func (m *MockFlowTool) Wait(toolCall providers.ToolCall) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", toolCall)
	ret0, _ := ret[0].(string)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockFlowToolMockRecorder) Wait(toolCall any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockFlowTool)(nil).Wait), toolCall)
}
